name: Automerge branches

env:
  SOURCE_BRANCH: master
  TARGET_BRANCH: develop

on:
  push:
    branches:
    - master # REPLACE WITH YOUR SOURCE BRANCH

jobs:
  automerge:
    name: Try to merge, fallback to pull request

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    ## Try to merge
    - name: merge
      uses: devmasx/merge-branch@v1.3.1
      with:
        github_token: ${{ github.token }}
        from_branch: ${{ env.SOURCE_BRANCH }}
        target_branch: ${{ env.TARGET_BRANCH }}
        type: now

    ## In case merging fails, then create a PR
    - name: pull-request
      uses: repo-sync/pull-request@v2.5
      if: ${{ failure() }}
      with:
        destination_branch: ${{ env.TARGET_BRANCH }}
        github_token: ${{ github.token }}
        pr_title: |
          Auto PR from ${{ env.SOURCE_BRANCH }} to ${{ env.TARGET_BRANCH }}
        pr_body: >
          :crown: This pull request was created automatically because there
          are changes in the *${{ env.SOURCE_BRANCH }}* branch that need to be
          merged with the *${{ env.TARGET_BRANCH }}* branch.
        pr_reviewer: ""
        pr_assignee: ""
        pr_label: "auto-pr"

    ## Print the URL of the pull request
    - name: output-url
      run: echo "Pull Request URL -> ${{ steps.open-pr.outputs.pr_url }}"
