name: Automerge branches

env:
  MAIN_BRANCH: main # Set your Main branch here
  MAJOR_VERSION: 3 # The current major version of the repo
  IGNORE_TARGETS: "example/1.1 example/1.2" # Comma separated list of target branches to ignore, is optional and can be removed
on:
  push:
    branches: # Set the branches that you want to trigger automerge for on push
      - main 
      - example/*
jobs:
  automerge:
    name: Try to merge, fallback to creating pull requests

    steps:
    - name Call automerge
      uses: meniga/.github/workflow/automerge@v1
      with:
        major-version: ${{ env.MAJOR_VERSION }}
        main-branch: ${{ env.MAIN_BRANCH }}
        ignore-targets: ${{ env.IGNORE_TARGETS }}
      secrets:
        github-token: ${{ secrets.AUTOMERGE_PAT }}
