name: Auto-merge branches

env:
  SOURCE_BRANCH: master
  TARGET_BRANCH: develop

on:
  push:
    branches:
    - master # REPLACE WITH YOUR SOURCE BRANCH

jobs:
  automerge:
    name: Merge source branch into target branch or create pull request on merge failure
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
    ##
    ## Try to merge
    - name: merge
      uses: mtanzi/action-automerge@v1
      id: merge
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source: ${{ env.SOURCE_BRANCH }}
        target: ${{ env.TARGET_BRANCH }}
        webhook_url: "" # If present add the Slack webhook
    ##
    ## In case merging fails, then create a PR
    - name: pull-request
      uses: repo-sync/pull-request@v2.5
      id: auto-pr
      if: ${{ failure() }}
      with:
        destination_branch: ${{ env.TARGET_BRANCH }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Auto PR from ${{ env.SOURCE_BRANCH }} to ${{ env.TARGET_BRANCH }}"
        pr_body: |
          :crown: This pull request was created automatically because there are changes in
          the *${{ env.SOURCE_BRANCH }}* branch that need to be merged with the *${{ env.TARGET_BRANCH }}* branch.
        pr_reviewer: ""
        pr_assignee: ""
        pr_label: "auto-pr"
    - name: output-url
      run: echo "Pull Request URL -> ${{ steps.open-pr.outputs.pr_url }}"
