name: Auto-merge branches

env:
  SOURCE_BRANCH: master
  TARGET_BRANCH: develop

on:
  push:
    branches:
    - ${{ env.SOURCE_BRANCH }}

jobs:
  automerge:
    name: Merge source branch into target branch or create pull request on merge failure
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
    ##
    ## Try to merge
    - name: merge
      uses: mtanzi/action-automerge@v1
      id: merge
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source: ${{ inputs.source_branch }}
        target: ${{ inputs.target_branch }}
        webhook_url: "" # If present add the Slack webhook
    ##
    ## In case merging fails, then create a PR
    - name: pull-request
      uses: repo-sync/pull-request@v2.5
      id: auto-pr
      if: ${{ failure() }}
      with:
        destination_branch: ${{ inputs.target_branch }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Auto PR from ${{ inputs.source_branch }} to ${{ inputs.target_branch }}"
        pr_body: |
          :crown: This pull request was created automatically because there are changes in
          the *${{ inputs.source_branch }}* branch that need to be merged with the *${{ inputs.target_branch }}* branch.
        pr_reviewer: ""
        pr_assignee: ""
        pr_label: "auto-pr"
    - name: output-url
      run: echo "Pull Request URL -> ${{ steps.open-pr.outputs.pr_url }}"
