name: Legacy TryCI

on:
  push:
    branches: ['**']
    tags: ['*']
    paths-ignore:
    - '.github/**'
    - '!.github/workflows/legacy-tryci.yaml'
    - 'docs/**'
    - '*.md'

jobs:
  ci:
    # This will execute the workflow on our self-hosted Windows WM
    runs-on: [self-hosted, Windows]

    steps:
    - uses: actions/checkout@v2
      # Uncomment to fetch all history for all branches and tags
      # with:
      #   fetch-depth: 0

    - name: Run TryCI task using psake
      run: psake tryci
