# In the last step that publishes a GitHub Release, be sure to adjust
# the 'files' argument with the correct path of the built artifacts
# that should be included in the release. Typically: build/Latest
name: Legacy CI

# What should trigger this workflow to be executed
on:
  # Define which push events should trigger this workflow
  push:
    # Trigger a build when pushing to any branch or when tagging
    branches: ['**']
    tags: ['*']

    # Except when the only files that changed match these patterns
    paths-ignore:
    # Ignore everything in the .github directory except the legacy-ci.yml workflow file
    - '.github/**'
    - '!.github/workflows/legacy-ci.yml'
    - 'docs/**'
    - '*.md'

  ## Uncomment to run this workflow every Friday at midnight
  #schedule:
  #- cron:  '0 0 * * FRI'

# The actual workflow
jobs:
  ci:
    # This will execute the workflow on our self-hosted Windows VM
    runs-on: [self-hosted, Windows]

    steps:
    - uses: actions/checkout@v2
      # Remove if you don't need to fetch all history for all branches and tags
      with:
        fetch-depth: 0

    # Remove this step if you are not using submodules
    #
    # Fetching submodules with the actions/checkout action fails because
    # it generates an invalid Windows path when storing the public SSH key
    # Tip: Add the --recursive flag if your submodules include other submodules
    - name: Update git submodules
      run: git submodule update --init

    # Adjust as needed, e.g. psake tryci to run the TryCI task
    - name: Run CI task using psake
      run: psake ci

    # For more information on how to customize the release
    # Ideally, you would for example supply the action with a body that
    # further explains the changes in the release
    # ref: https://github.com/softprops/action-gh-release#-customizing
    - name: Create release (if tag was pushed)
      if: startsWith(github.ref, 'refs/tags')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: false
        # Adjust as needed, should point to the path(s) where the CI step
        # outputs the built application/packages
        # Newline-delimited globs of paths to assets to upload for release
        files: build/Latest
