name: psake TryCI

on:
  # Run this workflow when a pull request is opened, synchronized (code changes)
  # and if a pull request is reopened
  pull_request:
    types: [opened, synchronize, reopened]

  # Enables manual triggering
  workflow_dispatch:

jobs:
  tryci:
    runs-on: [self-hosted, Windows]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Fetching submodules with the checkout step fails because
    # it generates an invalid Windows path when storing the public SSH key
    - name: Update git submodules
      run: git submodule update --init --recursive

    - name: Run TryCI task using psake
      run: psake tryci
