name: psake TryCI

on:
  push:
    # Run when pushing to any branch except for master
    # Adjust according to your project
    branches:
    - '**'
    - '!master'
    - '!develop'

    # Ignore changes made to these files
    paths-ignore:
    # Ignore everything in the .github directory except the psake-tryci.yml workflow file
    - '.github/**'
    - '!.github/workflows/psake-tryci.yml'

  # Enables manual triggering
  workflow_dispatch:

jobs:
  tryci:
    runs-on: [self-hosted, Windows]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Fetching submodules with the checkout step fails because
    # it generates an invalid Windows path when storing the public SSH key
    - name: Update git submodules
      run: git submodule update --init

    - name: Run TryCI task using psake
      run: psake tryci
